require:
  - rubocop-performance
  - rubocop-rspec

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MethodLength:
  Enabled: true
  Max: 20
